version: '3.8'

services:
  hunyuan3d-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - TEMP_DIR=/tmp/temp_3d
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN:-}
    volumes:
      - ./temp_data:/tmp/temp_3d
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G